### ISSUE TITLE
PyPi is wildly out of date

### ISSUE THREAD

**Issue by AnthonyBriggs** [jezdez/django-dbtemplates#51]
Hi,

I just ran into issue #33 while using the latest version of dbtemplates in PyPI (https://pypi.python.org/pypi/django-dbtemplates). It's at least two years out of date :(

**Comment by darkpixel** [comment]
+1

**Comment by michaelkuty** [comment]
will be soon, new release in progress

may i close this issue ?

**Comment by AnthonyBriggs** [comment]
Yep, looks good. Thanks! :)
