### ISSUE TITLE
Django 1.8 compatibility: fields or exclude required on TemplateAdminForm

### ISSUE THREAD

**Issue by jnns** [jezdez/django-dbtemplates#55]
A deprecation warning occurs with a current Django version: 

> […]/local/lib/python2.7/site-packages/dbtemplates/admin.py:72: 
> RemovedInDjango18Warning: 
> Creating a ModelForm without either the 'fields' attribute or the 'exclude' attribute is deprecated 
> form TemplateAdminForm needs updating

**Comment by michaelkuty** [comment]
fixed in #58
