### ISSUE TITLE
Unusable with django 1.8

### ISSUE THREAD

**Issue by elioscordo** [jezdez/django-dbtemplates#57]
Hi,
the app is not usable anymore:
It throws TypeError
__init__() takes exactly 2 arguments (1 given)
/django/template/loader.py in __init__, line 155

**Comment by michaelkuty** [comment]
try us fork https://github.com/michaelkuty/django-dbtemplates

**Comment by elioscordo** [comment]
Thanks... it works

**Comment by michaelkuty** [comment]
for more details see #58 support for Django 1.8 will be soon as possible

please can i close this issue ?

**Comment by elioscordo** [comment]
yes.. thank you !!!
